### ISSUE TITLE
用vs2015报 error LNK2019: 无法解析的外部符号

### ISSUE THREAD

**Issue by ruoshui1314** [tomwillow/2048#1]
2048.obj : error LNK2019: 无法解析的外部符号 **imp__InitCommonControls@0，该符号在函数 "long __stdcall WndProc(struct HWND** *,unsigned int,unsigned int,long)" (?WndProc@@YGJPAUHWND__@@IIJ@Z) 中被引用

没有太用过图形底层库.网上么有搜索到解决方案,可否帮忙看看

**Comment by tomwillow** [comment]
链接库加入comctl32.lib
或者在#include等句下加入#pragma comment(lib,"comctl32.lib")

**Comment by ruoshui1314** [comment]
OK~3q.这些库之前都没有用过.不太熟悉.
